name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main 
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 依存関係をインストール
        run: npm install

      - name: Run script
        run: node updateScript/checkEdited.js
        env:
          NOTION_TOKEN_HORIZON: ${{secrets.NOTION_TOKEN_HORIZON}}
          NOTION_DB_ID_HORIZON: ${{secrets.NOTION_DB_ID_HORIZON}}
          SUPABASE_ANON_KEY: ${{secrets.SUPABASE_ANON_KEY}}
          SUPABASE_URL: ${{secrets.SUPABASE_URL}}
          IFRAMELY_API_KEY: ${{secrets.IFRAMELY_API_KEY}}
          NOTION_DB_ID_CATEGORY: ${{secrets.NOTION_DB_ID_CATEGORY}}
      
      - name: Commit and push if changes exist
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Notion data [skip ci]"
          git push

      - name: Next.js をビルド
        if: success()
        run: npm run build
        env:
          NEXT_PUBLIC_AUTH0_DOMAIN: ${{secrets.NEXT_PUBLIC_AUTH0_DOMAIN}}
          NEXT_PUBLIC_AUTH0_CLIENT_ID: ${{secrets.NEXT_PUBLIC_AUTH0_CLIENT_ID}}
          NEXT_PUBLIC_ROOT_PATH: ${{secrets.NEXT_PUBLIC_ROOT_PATH}}
          SUPABASE_ANON_KEY: ${{secrets.SUPABASE_ANON_KEY}}
          SUPABASE_URL: ${{secrets.SUPABASE_URL}}
          NEXT_PUBLIC_RAILWAY_URL: ${{secrets.NEXT_PUBLIC_RAILWAY_URL}}
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{secrets.NEXT_PUBLIC_FIREBASE_API_KEY}}
          NEXT_PUBLIC_AUTH_DOMAIN: ${{secrets.NEXT_PUBLIC_AUTH_DOMAIN}}
          NEXT_PUBLIC_PROJECT_ID: ${{secrets.NEXT_PUBLIC_PROJECT_ID}}
          NEXT_PUBLIC_STORAGE_BUCKET: ${{secrets.NEXT_PUBLIC_STORAGE_BUCKET}}
          NEXT_PUBLIC_APP_ID: ${{secrets.NEXT_PUBLIC_APP_ID}}
          NEXT_PUBLIC_MESSAGING_SENDER_ID: ${{secrets.NEXT_PUBLIC_MESSAGING_SENDER_ID}}
          NEXT_PUBLIC_MEASUREMENT_ID: ${{secrets.NEXT_PUBLIC_MEASUREMENT_ID}}
          NEXT_PUBLIC_DISCORD_CLIENT_ID: ${{secrets.NEXT_PUBLIC_DISCORD_CLIENT_ID}}

      - name: gh-pages ブランチにデプロイ
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
